nelmio_api_doc:
  documentation:
    info:
      title: 'My API'
      description: 'Custom API documentation'
      version: '1.0.0'
    components:
      securitySchemes:
        Bearer:
          type: http
          scheme: bearer
          bearerFormat: JWT
    security:
      - Bearer: [ ]
  areas:
    default:
      path_patterns:
        - ^/api