controllers:
    resource: ../src/Controller/
    type: attribute

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

nelmio_api_doc_json:
    path: /api/doc.json
    controller: Nelmio\ApiDocBundle\Controller\SwaggerController
    methods: [GET]